name: CI

on:
  workflow_dispatch:
  push:
    branches:
      mainline
    paths-ignore:
      - '**.md'

permissions:
  contents: read

jobs:

  Test-Marqo:
    name: Run Marqo Test Suite
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
                
    environment: marqo-test-suite 
    
    steps:
       
      - name: Checkout marqo repo
        uses: actions/checkout@v3
          
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
          cache: "pip"
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
          driver-opts: network=host
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Build Marqo Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: localhost:5000/marqo/multiarch:latest
          
      - name: Checkout marqo-api-tests repo
        uses: actions/checkout@v3
        with:
          repository: marqo-ai/marqo-api-tests
          
      - name: Set up Environment
        run: |
          pip install tox
          # Set up conf file
          echo 'export MARQO_API_TESTS_ROOT="${{ github.workspace }}"' >> conf
          echo 'export S2SEARCH_URL="${{ secrets.S2SEARCH_URL }}"' >> conf
          
      - name: Run Unit Tests
        run: tox -e py3-local_os_unit_tests_w_requirements
        
      - name: Run Integration Tests - local_os
        run: tox -e py3-local_os 
        
      - name: Run Integration Tests - dind_os
        run: tox -e py3-dind_os
        
      - name: Run Integration Tests - s2search
        run: tox -e py3-s2search
